Problems Set-1:

A list baseball has already been defined in the below, representing the height of some baseball players in centimetres. Prepare this as a numpy array.
baseball= [180,215,210,210,188,176,209,200]

In [1]:
baseball= [180,215,210,210,188,176,209,200]

In [2]:
import numpy as np

In [3]:
np.array(baseball)

array([180, 215, 210, 210, 188, 176, 209, 200])

2. Name this new array np_height_in.

    a. Print np_height_in.

    b. Multiply np_height_in with 0.0254 to convert all height measurements from inches to metres. Store the new values in a new array, np_height_m.

    c. Print out np_height_m and check if the output makes sense.

In [4]:
#a
np_height_in = np.array(baseball)
print(np_height_in)

[180 215 210 210 188 176 209 200]


In [5]:
#b
np_height_m = 0.0254 * np_height_in
print(np_height_m)

[4.572  5.461  5.334  5.334  4.7752 4.4704 5.3086 5.08  ]


3. A list weight_lb has already been defined in the Python script below, representing the weight of some baseball players in pounds

    Weight_lb=[172,190,165,175,166,159,182,168]

  Create a numpy array from the weight_lb list with the correct units. Multiply by 0.453592 to go from pounds to kilograms. Store the resulting numpy array as np_weight_kg.

      a. Use np_height_m (given in Q#2) and np_weight_kg to calculate the BMI of each player. Use the following equation:BMI=weight (kg) / height (m)^2


      b. Save the resulting numpy array as bmi.

      c. Print out bmi.

In [6]:
Weight_lb=[172,190,165,175,166,159,182,168]

In [7]:
np_weight_kg = np.array(Weight_lb) * 0.453592

In [8]:
#a,b,c
bmi = np_weight_kg / np_height_m ** 2
print(bmi)

[3.73234164 2.88984556 2.6305303  2.78995637 3.30210092 3.60885757
 2.92938713 2.95288983]


4. Create a boolean numpy array: the element of the array should be True if the corresponding baseball player'sBMI is below 21. You can use the < operator for this. Name the array light.


      a. Print the array light.

      b. Print out a numpy array with the BMIs of all baseball players whose BMI is below 21.Use light inside square brackets to do a selection on the bmi array.e.g [light < 20]

In [9]:
#a
light = bmi < 21
print(light)

[ True  True  True  True  True  True  True  True]


In [10]:
#b
print(bmi[light==True])


[3.73234164 2.88984556 2.6305303  2.78995637 3.30210092 3.60885757
 2.92938713 2.95288983]


5. In this question, baseball is a list of lists. The main list contains 4 elements. Each of these elements is a list containing the height and the weight of 4 baseball players, in this order. baseball is already given here for you
baseball=[[180,78.4],[215,102.7],[210,98.5],[188,75.2]]

                  a. Use np.array() to create a 2D numpy array from baseball. Name it np_baseball.

                  b. Print out the type of np_baseball.

                  c. Print out the shape attribute of np_baseball. Use np_baseball.shape

In [11]:
baseball=[[180,78.4],[215,102.7],[210,98.5],[188,75.2]]

In [12]:
#a
np_baseball = np.array(baseball)

In [13]:
#b
print(np_baseball)

[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]


In [14]:
#b
np_baseball.dtype

dtype('float64')

In [15]:
#c
print(np_baseball.shape)

(4, 2)


6. You've contacted FIFA for some data and they handed you three lists. The lists are the following:

            height = np.round(np.random.normal(1.75, 0.20, 1000), 2)

            weight = np.round(np.random.normal(60.32, 15, 1000), 2)

            age = np.round(np.random.normal(30, 10, 1000), 0)

let’s stack it altogether
np_players = np.column_stack((height, weight, age))
Each element in the lists corresponds to a player. The first list, height, representing each player's height in metres. The second list, weight, represents each player's weight in kilograms. The third list, age,representing each player's age in years.


            a. Create a numpy array np_height that is equal to the first column of np_players.
            b. Print out the mean of np_height .
            c. Print out the median of np_height

In [16]:
height = np.round(np.random.normal(1.75, 0.20, 1000), 2) # Mean, SD, No. Of samples
height.shape

(1000,)

In [17]:
weight = np.round(np.random.normal(60.32, 15, 1000), 2)

In [18]:
age = np.round(np.random.normal(30, 10, 1000), 0)

In [19]:
np_players = np.column_stack((height, weight, age))

In [20]:
np_players.shape


(1000, 3)

In [21]:
#a
np_height = np_players[:,0]
#np_height

In [22]:
#b
print(np_height.mean())

1.76022


In [23]:
np.mean(np_height)

np.float64(1.76022)

In [24]:
#c
print(np.median(np_height))

1.76


Problems Set-2:

Generate 2D NumPy random array representing sales data (units sold) of 6 products over 8 weeks. Compute the following.

a. Weekly Total Sales: Compute the total sales for each week (column-wise sum).

b. Best-Selling Product: Find the product (row index) that sold the most units in total.

c. Top 2 Weeks for Each Product: For each product (row), extract the indices of the two highest-selling weeks.

d. Products Above Average

Compute the overall average sales (scalar). Return a Boolean mask of shape (6, 8) showing where sales exceed this average.

You can use the following numpy functions for solving.
sum, mean, argmax, argsort.

In [25]:
sales_data = np.random.randint(1, 10, size=(6, 8))
sales_data

array([[8, 5, 7, 3, 1, 5, 4, 2],
       [1, 2, 6, 8, 8, 2, 7, 5],
       [5, 3, 9, 3, 7, 7, 8, 6],
       [4, 7, 2, 7, 6, 8, 5, 9],
       [7, 2, 1, 8, 8, 5, 5, 2],
       [1, 4, 8, 9, 3, 7, 1, 9]])

In [26]:
#a
weekly_total_sales = np.sum(sales_data, axis=0)
weekly_total_sales

array([26, 23, 33, 38, 33, 34, 30, 33])

In [27]:
np.sum(sales_data, axis=1)

array([35, 39, 48, 48, 38, 42])

In [28]:
#b
best_selling_product = np.argmax(np.sum(sales_data, axis=1))
print(best_selling_product)

2


In [29]:
#c
top2weeks = np.argsort(sales_data, axis=1) #
top2weeks

array([[4, 7, 3, 6, 1, 5, 2, 0],
       [0, 1, 5, 7, 2, 6, 3, 4],
       [1, 3, 0, 7, 5, 4, 6, 2],
       [2, 0, 6, 4, 3, 1, 5, 7],
       [2, 1, 7, 5, 6, 0, 3, 4],
       [0, 6, 4, 1, 5, 2, 3, 7]])

In [30]:
top2weeks = np.argsort(sales_data, axis=1)[:, -2:]
print(top2weeks)


[[2 0]
 [3 4]
 [6 2]
 [5 7]
 [3 4]
 [3 7]]


In [31]:
#d
overall_avg_sell = np.mean(sales_data)
overall_avg_sell

np.float64(5.208333333333333)

In [32]:
#d
mask = sales_data > overall_avg_sell
mask

array([[ True, False,  True, False, False, False, False, False],
       [False, False,  True,  True,  True, False,  True, False],
       [False, False,  True, False,  True,  True,  True,  True],
       [False,  True, False,  True,  True,  True, False,  True],
       [ True, False, False,  True,  True, False, False, False],
       [False, False,  True,  True, False,  True, False,  True]])